export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as Contact} from './Contact'
export {default as About} from './About'
export {default as ProductsPage} from './ProductsPage'
export {default as Product} from './Product'
export {default as Cart} from './Cart'
export {default as Checkout} from './Checkout'
export {default as NotFound}from './NotFound'
